# This is a basic workflow to help you get started with Actions

name: unittest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#      - name: Install gtest manually
#        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: prepare env
        run: |
            echo "TRAVIS_BUILD_DIR=$PWD" >> $GITHUB_ENV
            echo "CMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/tests/install" >> $GITHUB_ENV
            echo "GTEST_ROOT=$CMAKE_PREFIX_PATH/googletest" >> $GITHUB_ENV
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Install tools
        run: |
            export CMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/tests/install
            export GTEST_ROOT=$CMAKE_PREFIX_PATH/googletest
            cd $GITHUB_WORKSPACE/tests/ci
            ./install_googletest.sh
            cd $GITHUB_WORKSPACE/tests/ci
            ./install_rapidassist.sh
            ls -l $GITHUB_WORKSPACE/tests/win32arduino
            cd $GITHUB_WORKSPACE/tests/ci
            ./build_win32arduino.sh
            cd $GITHUB_WORKSPACE/tests/ci
            ./build_signalDecoderTests.sh
            cd $GITHUB_WORKSPACE/
            ls -l
      - name: run test
        run: |
            cd $GITHUB_WORKSPACE/tests/build
            ls -l
            ./bin/TestProject 
